Repository simonw/datasette, pull requests merged in 2022-12, with the labels that each got.

#1931 /db/table/-/upsert
  datasette/app.py
  datasette/default_permissions.py
  datasette/views/special.py
  datasette/views/table.py
  docs/json_api.rst
  tests/test_api_write.py
Labels: json-api

#1961 Use click.echo() instead of print() for --root option
  datasette/cli.py
Labels: bug

#1967 Add favicon to documentation
  docs/_static/datasette-favicon.png
  docs/conf.py
Labels: documentation
