Repository simonw/datasette, pull requests merged in 2024-02, with the labels that each got.

#2257 table_config instead of table_metadata
  datasette/app.py
  datasette/database.py
  datasette/utils/__init__.py
  datasette/views/table.py
  tests/test_api.py
  tests/test_html.py
Labels: refactor

#2268 fix (typo): Corrected spelling of 'environments'
  .github/workflows/spellcheck.yml
  Justfile
  docs/codespell-ignore-words.txt
  tests/test-datasette-load-plugins.sh
Labels: documentation

#2282 New design for table and database action menus
  datasette/static/app.css
  datasette/templates/database.html
  datasette/templates/patterns.html
  datasette/templates/table.html
Labels: design

#2288 `query_actions` plugin hook, refs #2283
  datasette/hookspecs.py
  datasette/templates/query.html
  datasette/views/database.py
  docs/plugin_hooks.rst
  tests/fixtures.py
  tests/plugins/my_plugin.py
  tests/test_plugins.py
Labels: enhancement, plugins
